#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

# check if parameter are 4 or less and display a message if less than 3 params
if [ "$#" -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# assign parameter to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# use scp; to transfer file to server through ssh
scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
# rechecking if the transfer file was successful
if [ $? -eq 0 ]
then 
  echo "FILE TRANSFER WAS SUCCESSFUL"
else
  echo "FILE TRANSFER FAILED"
fi
