#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

transfer_file="$1"
server_ip="$2"
private_key="$3"
username="$4"

if ["$# -lt 4" ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
else
	scp -o StrictHostKeyChecking=no -i "$3" "$1" "$4"@"$2"
fi
