#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:

if ["$# -lt 4" ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

transfer_file='~/.ssh/school'
server_ip='18.209.223.78'
private_key='~/.ssh/id_rsa'
username='ubuntu'
scp -o StrictHostKeyChecking=no -i "$private_key" "$transfer_file" "$username"@"$server_ip"
