#!/usr/bin/env bash

#Install nginx on your web-01

sudo apt-get update
sudo apt-get -y install nginx

# configuring to allow incoming traffic
sudo ufw allow 'nginx HTTP'
# creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# testing nginx configuration syntax
sudo nginx -t

#reload and apply changes
sudo service nginx start
