#!/usr/bin/env bash

# Install nginx on your web-01
# server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
#  using curl, it must return a page that contains the string Hello World!
# As an answer file, write a Bash script that configures a new Ubuntu
#  machine to respect above requirements (this script will be run on the server itself)
# You can’t use systemctl for restarting nginx

#install nginx
sudo apt-get --update
sudo apt-get -y install nginx

# simple hello-world html page
echo '<!DOCTYPE html>
<html lang="en">
<head>
	<title>Hello World</title>
</head>
<body>
	<h1>Hello World<h1>
</body>
</html>' | sudo tee /var/www/html/hello_world.html

sudo nginx -t

#reload and apply changes
sudo service nginx reload
