#!/usr/bin/env bash
#install nginx on your web-01

sudo apt-get update
sudo apt-get -y install nginx
# get hostname
hostname = $(hostname)

# configuring to allow incoming traffic, allow both HTTP and HTTPS(full)
sudo ufw allow 'nginx HTTP'
# creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html && sudo sed -i 's/\(listen\s*80;\)/\1 listen 80;/'

sudo bash -c "echo 'add_header X-Served-By $hostname;' > /etc/nginx/sites-available/default"
# testing nginx configuration syntax

sudo nginx -t

#reload and apply changes
sudo service nginx reload
