#!/usr/bin/env bash
#install nginx on your web-01

sudo apt-get update
sudo apt-get -y install nginx
# get hostname
hostname=$(hostname)

# configuring to allow incoming traffic, allow both HTTP and HTTPS(full)
sudo ufw allow 'nginx HTTP'
# creating an index.html page
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo sed -i '/listen\s*80;/a \\nserver {\n listen 80;\n server_name _;\n location /redirect_me {\n return 301 https://www.youtube.com/watch?v=7VAI73roXaY;\n }\n}' /etc/nginx/sites-available/default

#sudo sed -i 's/\(listen\s*80;\)/\1 listen 80;/' /etc/nginx/sites-available/default 
# testing nginx configuration syntax
sudo nginx -t

#reload and apply changes
sudo service nginx reload
