#!/usr/bin/env bash
# adding the custom header
hostname=$(hostname)

# Configure Nginx to add a custom response header
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes

sudo service nginx restart
