#!/usr/bin/env bash
#
#install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy
# install required packages
sudo apt-get -y install software-properties-common

# Set hostname for web-01
echo '206429-web-01' | sudo tee /etc/hostname
sudo hostnamectl set-hostname 206429-web-01

# Set hostname for web-02
echo '206429-web-02' | sudo tee /etc/hostname
sudo hostnamectl set-hostname 206429-web-02

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend hapfront
    bind *:80
    mode http
    default_backend hapset

backend hapset
    mode http
    balance roundrobin
    server 206429-web-01 34.207.58.78:80 check
    server 206429-web-02 18.209.225.212:80 check
EOF
# Add your HAProxy configuration to haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}

# Restart HAProxy to apply changes
sudo service haproxy restart
