#!/usr/bin/env bash
# script displays the time for 12 hrs and 59 mins
# Displays hrs from 0 to 12
# Displays mins from 1 to 59
# Must use the while loop

hr=0

while [ $hr -le 12 ]
do
	echo "Hour: $hr"

	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( hr++))
done
