#!/usr/bin/env bash
#check if script is running in a docker container
if [ -f /.dockerenv ]; then
    #add mapping for localhost
    echo "127.0.0.2 localhost" >> /etc/hosts
    #add mapping for facebook
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
