#!/usr/bin/env bash
# running nginx as a nginx user
sudo adduser --system --no-create-home --disabled-login --ingroup sudo nginx && sudo usermod -aG sudo nginx
nginx_conf="/etc/nginx/sites-available/default" # Configuration file for Nginx
sed -i 'listen/s/80 default_server/8080 default_server/' "$nginx_conf" # Set Nginx to listen on all active IPs on port 8080
