#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private key
server_ip='100.26.241.49'
username='ubuntu'
private_key='~/.ssh/school'

ssh -i "$private_key" "$username"@"$server_ip"
